language: android
jdk: oraclejdk7
os:
- linux
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra
  - extra-android-m2repository
env:
  matrix:
  - ANDROID_SDKS=android-23,sysimg-23  ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
  global:
  - secure: Qndv42LIywNUFCj1SKJIqX3U+kBFVGDz66rzocV2jBFKW72QoObjsGl0GXzolRaB1UF80jOnQwta6x2T/X1Adki3pY2XaxUXICmN0LlpZflntOxLnaxBSuHYcfFhOy+MIS3zrQP5pVbmey1D5InpR31q+3XKcTf4/mm4lsprq9j5y8o1C73yGda4nyOzK6ubxjHGkrcu+PWAgWmbxOCdRrscWIIEmqlZ8yOxmtMpcyTuKdeqs9ymWjI5sSYe7pVvAEO59CLT7eBtrXsSaglfkKYK/JgyZtIHVqDHk61y/s6ZYuyQ1f0QjZQocOF1x3WRuHsoWv98bKDN035rmG5BMW8wSKGKbzn9wjMGMHoE5Gh6+dYz+xw0rBAi+GQ/LsvaO6Gpd6xgh7fYC20Zxr/YdqIlL3GuN9R5K3kM3WSfK8hMc1oXU9qEdnSZwp0MlukCwT1fyspSoiDDS4yPvoY2C6TPj2zlvucpd+wODQUAsk+ntnC5H37Q+qtwKzryVSyundsAYRLY3FIlW8kA1BmuEqsrM0PDCBDr6tufRU2Rd8C+aZBDaQyegAsEfkT1+xX9+xanxEWj2cOaqSx8YxUc6WuG2YgUCn0cXEdW6JsdTITGXN9gWGx3m5vUu++JNO7pqSHz0PGnNZnV5+C3iavs6rC+0y2dA3XP56BopWdV6cY=
  - secure: EuusIgkz1EAfucMwEhPyEkSfFusOoIxidKukawIeFpKHMl4o9mha3JsMRDDSn5FjXOh0A8AwpG0MjkDpOjjTcr97J/HarnpM4F7hB49oiAbC+1U19NfNJOl1AYeBHSQ+X7vfYQILjt4mm2kAaxQiEnwvIb95tnWlX2EFe4ZBXmc02n1+VlXrnJ9vYAWDTySRqDfMxyPWWKkkgxYwui1ivIFo1aDIuD2nES5DEkL7sYWRbFwFLr3qb4rDNobKRlLMjfrsq4KcfMIK8wPTeRMB5FmpShYXMS6Ayt+N/afhVT1onqnMP6MRqelTtEf9iQ29hn/ZlOYJcNMKUQ21iE/VGL/QmdbJN1FO9OWhDbDw+hCPICcBraZlsGJx4GU447Mf3h+Kdd6PDtFyUh2TiZAVbm9uhs9boOIA5hFH5ZgsV2byvmMGMBQhEQG1ZUICUIbWCbzBk1vnGJiUilM1XXY8phdqo0gSAidzmhlmXOdOWuo3Amz4eR0n5Rt7tR7TxgiRGbrZzznAI4Dzc8mq68dejSxpccOIVeOSKmlKaIu3Dwq5zKQwGDWd6Rjy/GQWLXGj7/4jZkmPC2YrYGktYZ1Ms6Y2OIiUM1ycC04AVPBzk6cGR5cWqelFj+JyQRLpUh8mczBcgdDLq/8X5tHKyPVGbodSbMGpqndbgVlLAqsrQew=
  - secure: RxtH1Ixh60Yz3CScflZWTZqOd+2SMfZFZCcJHMj6+ySTIa8qcEiACaQJ6disbwxx6p1HM2oIjndpXM+slvtsm/MmA16KigvoUaS3m89C6g8nX8vB9PdIMliL01tSupF1B6Q/4NGdyfjymO2n0GycNPDUjDfs3fqhZaBLIrNQxjY/KqtZGfqoRkbrbxTzXcus4lPbugwtnLzQn629tijtTiNjdy9RmGOVpCynuaFSK5R0XVz9vVOO2mkIVTLaPWJHasDPhwLeH9cV/JzGwpkbF8oitpWvdo0xmQJW7h9Bp56m0M48baef8nCiIhYbbkLL/g93WllpaIxTL6nJj9IQabIZUF/oQVdvjPxokkbRVIgbbdfBH6heMLKl+iVJbnAeAqiWWv5X65yx3WZ+xy5j1ZGg1vUPOyndQ79VGUUA+b+NIlr72RmBzZGHT9kQlK1MuLa5PZUKSbSg3B4S1D/B5yPwGIE0K3Q2Jbbph00WOGMC+Uwz2tO8mx4lXv67LZBKva+xVeRsUgnWszgoYknPeAD4QkMPLO9Mcj6bZJsrn6f5bCFhx6imvEncq+XE6XofGO7PPP/umJr9mmStZBn9GZMq1+tcErAIas1Ki++Lt2UPQunNpR3DpW10VsBNT/lm+vdLqfu3E1AVdqMb3RyiBcKIBC7jGQLziQD4o0i2mD8=
  - secure: nlFF/HL/MWqIuI80n9Q42eWTdbewwyY8g1basyjQ0lw6MWcOR7T2QoXA4OQkAatD6KlBswx4mJEpVBmkALVAHw3cV9eSgX3KV/dFwjYE8mn8a/PgbekNqAEb80tmHXjiMxnLkcpD2JcV5uWfJhpCzsOtHAgbBxlSGhGLsOScF6Ts2HZTqHdil0pl/T5GK7YiLg5q7+heqDIN7OEApy+hl9OhMcesSPMIopflDUO36/bkK6CsuucYnQXYbJ7xmwuudRvfqqrEF2LxPMT35l8YymwPJwUhXcyW5D+KB8hAhBgws9hudrDV2RbywJAmhEYVKBlLBtyM1h4nW6GsWXxXepC0bPMihYds/JYdwZTABhL17CctSMId0K+YdPw5CHFQviHQ6KGK1SAqCIaip7NlRWiBOJdAfmFJ7lGB4bZHFh9f8sUN+zsHIxZSly8K5lB4aPhlHwodUHxVmUSL4xqvvgrLr/3xJ3rweMsy+kIJi4NyNhGcyvbNFrsg2Lrbg/Zkm8JQYpE4EmlSN8mTEUBDUYvPyXJBT6JHnNOFJN7yTTyRvR94sLI0s3/Zp19+/46TdIj4g9vd1JL4UmXPMs2h6JqMoqp3gd+t0MI2MSMp8hiA8aMobTFVunPOZgtl3J4bgbuugc3flyIKMtpYxNFGA8K+JqvUIjWdoL3QEj6BLxg=
before_install:
- chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: d1ZTuvOpNfiQkqbsmIHykZvpdDhnIoYyfZGO3TKGxtayB4n0r8Nyl3HuQAJXS4CCCjYcfKPDD68U6rx/E4YM//5j3+X6GfaMSllbdUzi01XBDGs9WLFg3cPh3ir0zeeIUiZEcW5y93Pl/7jxK/f9wGrCawwVfHF7QR2OEkoTP+AQ7EcoK/jmYHnFAzxO97evixEoHxlgg9vQOkAbRoXxvk4QunnJXtk0HQmjkZMVDxB70nusb99QSqK0mzfXayFA/ezKdQDnvSvlym676Zdg0MbBKnm/XsSnM/uxy7Y42t1tcLpw0M2h2G1k0k7I1vBPomd2HhjmfL1BCQ9kuefNK7E8fE3Jc+m/VrK0kXOmhq5dDHFiPO8V0Zrno12Ls9PWlOCucx+wmVv/FTSEALwovnw6L9RtAwM3UaiWzhm/0SGTF9ZsRqYZQIwR1Pah9DZuJczzfCDjKF8GhUbfvGQP/R9O8pmlvEfo4cV+bOqvC6IC8CZ6DVrhvjSyeGh27Tdv7qzkM+E/O1222X+lFvASeMXiwiaZ20YGspVljm5S2PVV5CO6v3mZI2sSAatOf0dkUStXtN47qtV45P2fNHDTlxgRX4CAtLtcysgaXkDhii60qnR5/Aybq/O2Oq34QEPDP/fZNv6CoMZouH476T/PNs+7EIlsgPsZEutkwYGq7yo=
  file_glob: true
  file: build/outputs/apk/*-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
script:
- ./gradlew clean build assembleRelease
notifications:
  hipchat:
    rooms:
      secure: LID0hT7TiQUAhp+1ZOU9EMGZlSGtA2SCYXhGPymX2loz5rSkolMov0YTXLEdNsJZQE1SbwN256j3d4hCf2HYcltnPO8eW/fvytGEl/K6DbVfwLWlqzh7285dIOJbcv4d0+0OKy305FA1Rf4bjJcasAnX1heY6P6zYVqcu09qv3OdMoaWh4jxQryt++WgHK8F4I56DucRNyhD0omiFgAzHr8WsD0fdMfoK4DYGahyXocne2TYT8dZhR+NWlz1YY/vYlyfXETuXiW794pLwMyeIX4sppiMSyEPkCLSiywxVC2dMg0LuPTdfrpiC7rWjdW+3CdhZQbGgg5pY1qKj+uZq4Cm9LtVHvOcYddJsSoz8MsRKZ5vh0YYeHjkvWKSSPiAoF+9eOSffkBjub4kBYX9Uu95BPz/NJMl0DJGeJkpz9L/R2vzSV3B8t+CGiavO0opCmkhrrXtdb2zfNnJigu0I0OvZdu4Pfg0ggzjR51ug+18sTTPkN1HmfFwuKvimfiF/SnWDW/7qYlTONGxEEszN+3r3yJDkfYWmS3IdbFTOxKFgO0sIYlYsj/b5AvAiu/s3b83uFv0QBUiIZxrS/pujoNPnPL7Sez9Z4onEm7/9E1FLTpSkQNHzEStj0scQPNZ6WdYkUH/SkGM6hegnhRz9rW4ANABerBtBBfzQI9M4+s=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    format: html
    notify: true
