language: android
jdk: oraclejdk7

os:
  - linux

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra
  - extra-android-m2repository


env:
  matrix:
    - ANDROID_SDKS=android-23,sysimg-23  ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

before_install:
 - chmod a+x gradlew

deploy:
 provider: releases
 api_key: "d84de92c2831e69bac8df19ae910d63f76116d4b"
 file_glob: true
 file: "build/outputs/aar/*.aar"
 skip_cleanup: true
 on:
   tags: true
   all_branches: true

script:
  - ./gradlew clean build assemble