language: android
jdk: oraclejdk7
os:
- linux
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra
  - extra-android-m2repository
env:
  matrix:
  - ANDROID_SDKS=android-23,sysimg-23  ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

before_install:
- chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: d1ZTuvOpNfiQkqbsmIHykZvpdDhnIoYyfZGO3TKGxtayB4n0r8Nyl3HuQAJXS4CCCjYcfKPDD68U6rx/E4YM//5j3+X6GfaMSllbdUzi01XBDGs9WLFg3cPh3ir0zeeIUiZEcW5y93Pl/7jxK/f9wGrCawwVfHF7QR2OEkoTP+AQ7EcoK/jmYHnFAzxO97evixEoHxlgg9vQOkAbRoXxvk4QunnJXtk0HQmjkZMVDxB70nusb99QSqK0mzfXayFA/ezKdQDnvSvlym676Zdg0MbBKnm/XsSnM/uxy7Y42t1tcLpw0M2h2G1k0k7I1vBPomd2HhjmfL1BCQ9kuefNK7E8fE3Jc+m/VrK0kXOmhq5dDHFiPO8V0Zrno12Ls9PWlOCucx+wmVv/FTSEALwovnw6L9RtAwM3UaiWzhm/0SGTF9ZsRqYZQIwR1Pah9DZuJczzfCDjKF8GhUbfvGQP/R9O8pmlvEfo4cV+bOqvC6IC8CZ6DVrhvjSyeGh27Tdv7qzkM+E/O1222X+lFvASeMXiwiaZ20YGspVljm5S2PVV5CO6v3mZI2sSAatOf0dkUStXtN47qtV45P2fNHDTlxgRX4CAtLtcysgaXkDhii60qnR5/Aybq/O2Oq34QEPDP/fZNv6CoMZouH476T/PNs+7EIlsgPsZEutkwYGq7yo=
  file_glob:   true
  file: c4d/build/outputs/apk/*.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
script:
- ./gradlew clean build assemble
notifications:
  hipchat:
    rooms:
      secure: LID0hT7TiQUAhp+1ZOU9EMGZlSGtA2SCYXhGPymX2loz5rSkolMov0YTXLEdNsJZQE1SbwN256j3d4hCf2HYcltnPO8eW/fvytGEl/K6DbVfwLWlqzh7285dIOJbcv4d0+0OKy305FA1Rf4bjJcasAnX1heY6P6zYVqcu09qv3OdMoaWh4jxQryt++WgHK8F4I56DucRNyhD0omiFgAzHr8WsD0fdMfoK4DYGahyXocne2TYT8dZhR+NWlz1YY/vYlyfXETuXiW794pLwMyeIX4sppiMSyEPkCLSiywxVC2dMg0LuPTdfrpiC7rWjdW+3CdhZQbGgg5pY1qKj+uZq4Cm9LtVHvOcYddJsSoz8MsRKZ5vh0YYeHjkvWKSSPiAoF+9eOSffkBjub4kBYX9Uu95BPz/NJMl0DJGeJkpz9L/R2vzSV3B8t+CGiavO0opCmkhrrXtdb2zfNnJigu0I0OvZdu4Pfg0ggzjR51ug+18sTTPkN1HmfFwuKvimfiF/SnWDW/7qYlTONGxEEszN+3r3yJDkfYWmS3IdbFTOxKFgO0sIYlYsj/b5AvAiu/s3b83uFv0QBUiIZxrS/pujoNPnPL7Sez9Z4onEm7/9E1FLTpSkQNHzEStj0scQPNZ6WdYkUH/SkGM6hegnhRz9rW4ANABerBtBBfzQI9M4+s=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    format: html
    notify: true
